import React from "react";

const AnimeList = [
    {
        src:'https:\/\/cdn.noitatnemucod.net\/thumbnail\/300x400\/100\/bcd84731a3eda4f4a306250769675065.jpg',
        title:'One Piece',
        info:'Gol D. Roger was known as the "Pirate King," the strongest and most infamous being to have sailed the Grand Line. The capture and death of Roger by th...',
        otherNames:'One Piece',
        Type:'tv-series',
        DateAired:'1999',
        Year:'Fall 2022 Anime',
        Status:'Ongoing Anime',
    },
    {
        src:'https:\/\/cdn.noitatnemucod.net\/thumbnail\/300x400\/100\/9cbcf87f54194742e7686119089478f8.jpg',
        title:'Naruto: Shippuden',
        info:'It has been two and a half years since Naruto Uzumaki left Konohagakure, the Hidden Leaf Village, for intense training...',
        OtherNames:'Naruto Shippuden',
        Type:'tv-series',
        DateAired:'2007',
        Year:'Fall 2022 Anime',
        Status:'Completed Anime',
    },
    {
        src:'https:\/\/cdn.noitatnemucod.net\/thumbnail\/300x400\/100\/bd5ae1d387a59c5abcf5e1a6a616728c.jpg',
        title:'Bleach',
        info:'A 15 year-old teenager named Kurosaki Ichigo has the ability to see the undead/ghosts/spirits. The journey begins...',
        OtherNames:'Bleach',
        Type:'tv-series',
        DateAired:'2012',
        Year:'Fall 2022 Anime',
        Status:'Completed Anime',
    },
    {
        src:'https:\/\/cdn.noitatnemucod.net\/thumbnail\/300x400\/100\/b51f863b05f30576cf9d85fa9b911bb5.png',
        title:'Jujutsu Kaisen',
        info:'In a world where demons feed on unsuspecting humans, fragments of the legendary and feared demon Ryoumen Sukuna were lost and scattered about. Should ...',
        OtherNames:'Jujutsu Kaisen',
        Type:'fall-2020-anime',
        DateAired:'2020',
        Year:'Fall 2020 Anime',
        Status:'Completed Anime',
    },
    {
        src:'https:\/\/cdn.noitatnemucod.net\/thumbnail\/300x400\/100\/f58b0204c20ae3310f65ae7b8cb9987e.jpg',
        title:'Black Clover',
        info:'An OVA episode bundled with the 11th manga volume.',
        OtherNames:'Black Clover',
        Type:'special',
        DateAired:'2016',
        Year:'Fall 2022 Anime',
        Status:'Completed Anime',
    },
    {
        src:'https:\/\/cdn.noitatnemucod.net\/thumbnail\/300x400\/100\/db2f3ce7b9cab7fdc160b005bffb899a.png',
        title:'Demon Slayer: Kimetsu no Yaiba Swordsmith Village Arc',
        info:'Swordsmith Village Arc of Kimetsu no Yaiba.',
        OtherNames:'Demon Slayer: Kimetsu no Yaiba Swordsmith Village Arc (Dub)',
        Type:'spring-2023-anime',
        DateAired:'2023',
        Year:'Fall 2022 Anime',
        Status:'Ongoing Anime',
    },
    {
        src:'https:\/\/cdn.noitatnemucod.net\/thumbnail\/300x400\/100\/32c83e2ad4a43229996356840db3982c.jpg',
        title:'Boruto: Naruto Next Generations',
        info:'Naruto was a young shinobi with an incorrigible knack for mischief. He achieved his dream to become the greatest ninja in...',
        OtherNames:'Boruto: Naruto Next Generations',
        Type:'spring-2017-anime',
        DateAired:'2017',
        Year:'Fall 2022 Anime',
        Status:'Ongoing Anime',
    },
    {
        src:'https:\/\/cdn.noitatnemucod.net\/thumbnail\/300x400\/100\/5db400c33f7494bc8ae96f9e634958d0.jpg',
        title:'Naruto',
        info:'Ninjas with bloodline limits begin disappearing in all the countries and blame points toward the fire nation. By Tsunade...',
        otherNames:'Naruto',
        Type:'movie',
        DateAired:'2009',
        Year:'Fall 2022 Anime',
        Status:'Completed Anime',
    },
    {
        src:'https:\/\/cdn.noitatnemucod.net\/thumbnail\/300x400\/100\/82402f796b7d84d7071ab1e03ff7747a.jpg',
        title:'Jujutsu Kaisen (TV)',
        info:'In a world where demons feed on unsuspecting humans, fragments of the legendary and feared demon Ryoumen Sukuna were lost and scattered about. Should ...',
        OtherNames:'Jujutsu Kaisen (TV)',
        Type:'fall-2020-anime',
        DateAired:'2020',
        Year:'Fall 2020 Anime',
        Status:'Completed Anime',
    },
    {
        src:'https:\/\/cdn.noitatnemucod.net\/thumbnail\/300x400\/100\/88bd17534dc4884f23027035d23d74e5.jpg',
        title:'Spy x Family',
        info:'For the agent known as "Twilight," no order is too tall if it is for the sake of peace. Operating as Westalis master spy, Twilight...',
        OtherNames:'Spy x Family',
        Type:'spring-2022-anime',
        DateAired:'2022',
        Year:'Fall 2022 Anime',
        Status:'Completed Anime',
    },
    {
        src:'https:\/\/cdn.noitatnemucod.net\/thumbnail\/300x400\/100\/b147d331e311a5d5c8ee81269725fc92.png',
        title:'Solo Leveling',
        info:'Sung Jin-woo, known as the weakest hunter, struggles to survive. After a near-death experience, however, he comes back with a mysterious program that significantly levels up his abilities...',
        OtherNames:'Solo Leveling',
        Type:'Anime',
        DateAired:'2024',
        Year:'2024 Anime',
        Status:'Completed Anime',
    },
    {
        src:'https:\/\/cdn.noitatnemucod.net\/thumbnail\/300x400\/100\/993c0361975cce4c7fbb11f8558f9664.jpg',
        title:'Hunter x Hunter',
        info:'Gon Freecs, a young boy that lives on a small island learns that his father who he doesn’t remember is an extremely famous...',
        OtherNames:'Hunter X Hunter',
        Type:'tv-series',
        DateAired:'1999',
        Year:'Fall 2022 Anime',
        Status:'Completed Anime',
    },
    {
        src:'https:\/\/cdn.noitatnemucod.net\/thumbnail\/300x400\/100\/fced51e392ffd80041b3a1581ba7de2f.jpg',
        title:'Blue Lock',
        info:'After reflecting on the current state of Japanese soccer, the Japanese Football Association decides to hire the enigmatic...',
        OtherNames:'Blue Lock',
        Type:'fall-2022-anime',
        DateAired:'2022',
        Year:'Fall 2022 Anime',
        Status:'Ongoing Anime',
    },
    {
        src:'https:\/\/cdn.noitatnemucod.net\/thumbnail\/300x400\/100\/3e13d0ab2ce8799c9da8ed59548b96e9.jpg',
        title:'Demon Slayer: Entertainment District Arc',
        info:'A youth begins a quest to fight demons and save his sister after he finds his family slaughtered and his sister turned into a demon...',
        OtherNames:'Demon Slayer: Entertainment District Arc',
        Type:'Anime',
        DateAired:'2019',
        Year:'2022 Anime',
        Status:'Completed Anime',
    },
    {
        src:'https:\/\/cdn.noitatnemucod.net\/thumbnail\/300x400\/100\/debf027d032c6d40b91fab16b2ff9bd4.jpg',
        title:'Attack on Titan',
        info:'Eren Jaeger, along with his sister and friends, joins the military in order to destroy the Titans, gigantic humanoids who live off human flesh.',
        OtherNames:'Attack on Titan',
        Type:'Anime',
        DateAried:'2013',
        Year:'2023 Anime',
        Status:'Completed Anime',

    },
    {
        src:'https:\/\/cdn.noitatnemucod.net\/thumbnail\/300x400\/100\/30df93feaa422101659e14d0a2a2f582.jpg',
        title:'Demon Slayer: Kimetsu no Yaiba',
        info:'Swordsmith Village Arc of Kimetsu no Yaiba.',
        OtherNames:'Demon Slayer: Kimetsu no Yaiba Swordsmith Village Arc (Dub)',
        Type:'spring-2023-anime',
        DateAired:'2023',
        Year:'Fall 2022 Anime',
        Status:'Ongoing Anime',
    },
    {
        src:'https:\/\/cdn.noitatnemucod.net\/thumbnail\/300x400\/100\/20b7580c1abdf45a6eaf4826fc9fdf33.jpg',
        title:'My Hero Academia Season 6',
        info:'Sixth season of Boku no Hero Academia.',
        OtherNames:'Boku no Hero Academia 6th Season',
        Type:'fall-2022-anime',
        DateAired:'2022',
        Year:'Fall 2022 Anime',
        Status:'Ongoing Anime',
    },
    {
        src:'https:\/\/cdn.noitatnemucod.net\/thumbnail\/300x400\/100\/8ed3a4df2e8f22be9916959c96e5e3e2.jpg',
        title:'Blue Lock',
        info:'After demonstrating his overwhelming soccer talent, high school sophomore Seishiro Nagi receives an invitation to the Blue Lock Project and meets strikers from all over the country.',
        OtherNames:'Blue Lock',
        Type:'Anime',
        DateAired:'2024',
        Year:'2024 Anime',
        Status:'Ongoing Anime',
    },
    
];
export default AnimeList;